apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-service
spec:
  selector:
    matchLabels:
      app: conversion-service
  replicas: 1
  template:
    metadata:
      name: conversion-pod
      labels:
        app: conversion-service
    spec:
      containers:
      - name: conversion-pod
        image: umesh0166/conversion-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-lb
spec:
  selector:
    app: conversion-service
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8100
  type: LoadBalancer
