apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-service
spec:
  selector:
    matchLabels:
      app: currency-exchange-service
  replicas: 1
  template:
    metadata:
      labels:
        app: currency-exchange-service
    spec:
      containers:
      - name: currency-exchange-service
        image: umesh0166/currency-exchange-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-lb
spec:
  selector:
    app: currency-exchange-service
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8000
  type: LoadBalancer
