apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion-service
spec:
  selector:
    matchLabels:
      app: currency-conversion-service
  replicas: 2
  template:
    metadata:
      labels:
        app: currency-conversion-service
    spec:
      containers:
      - name: currency-conversion-service
        image: umesh0166/currency-conversion-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-lb
spec:
  selector:
    app: currency-conversion-service
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8100
  type: LoadBalancer
