apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-customer-service
spec:
  selector:
    matchLabels:
      app: fin-customer-service
  replicas: 2
  template:
    metadata:
      labels:
        app: fin-customer-service
    spec:
      containers:
      - name: fin-customer-service
        image: umesh0166/fin-customer-service:latest
