apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-customer-service
spec:
  selector:
    matchLabels:
      app: fin-customer-service
  replicas: 2
  template:
    metadata:
      labels:
        app: fin-customer-service
    spec:
      containers:
      - name: fin-customer-service
        image: umesh0166/fin-customer-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: fin-customer-lb
spec:
  selector:
    app: fin-customer-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5000
  type: LoadBalancer
