apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-pod
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8081
          - name: jnlp-port
            containerPort: 5000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
      volumes:
        - name: jenkins-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8081
  type: LoadBalancer
