apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-transaction-service
spec:
  selector:
    matchLabels:
      app: retail-transaction-service
  replicas: 1
  template:
    metadata:
      name: retail-transaction-pod
      labels:
        app: retail-transaction-service
    spec:
      containers:
      - name: retail-transaction-pod
        image: umesh0166/retail-transaction-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: retail-transaction-lb
spec:
  selector:
    app: retail-transaction-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
